package src;
import java.io.File;
import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.FileInputStream;import java.io.InputStreamReader;import java.io.BufferedReader;import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;
import src.Regexer;
import src.automatons.Automaton;
import src.automatons.DFA;
import src.automatons.NFA;
import src.automatons.NFABuilder;
import src.automatons.Pair;
import src.automatons.State;
import src.automatons.Symbol;
import src.scanner.Scanner;
import src.scanner.Token;

public class drk implements Scanner {
     private DFA dfa;
     private BufferedReader reader;
     private int currentCharacter;
     private int nextCharacter;
     private ArrayList<String> excepts;
     Set<String> excepted;

     public drk(File file) throws Exception {
         reader = new BufferedReader(new InputStreamReader(new FileInputStream(file), "UTF-8"));
         consume();
         dfa = new DFA();
         State s1 = new State("1");
         dfa.addState(s1);
         dfa.changeInitialState(s1);
         State s2 = new State("2");
         dfa.addState(s2);
         s2.setAttached("IDENT");
         dfa.addAcceptingState(s2);
         State s3 = new State("3");
         dfa.addState(s3);
         s3.setAttached("IDENT");
         dfa.addAcceptingState(s3);
         State s4 = new State("4");
         dfa.addState(s4);
         s4.setAttached("IDENT");
         dfa.addAcceptingState(s4);
         State s5 = new State("5");
         dfa.addState(s5);
         s5.setAttached("IDENT");
         dfa.addAcceptingState(s5);
         State s6 = new State("6");
         dfa.addState(s6);
         s6.setAttached("IDENT");
         dfa.addAcceptingState(s6);
         State s7 = new State("7");
         dfa.addState(s7);
         s7.setAttached("IDENT");
         dfa.addAcceptingState(s7);
         State s8 = new State("8");
         dfa.addState(s8);
         s8.setAttached("IDENT");
         dfa.addAcceptingState(s8);
         State s9 = new State("9");
         dfa.addState(s9);
         s9.setAttached("IDENT");
         dfa.addAcceptingState(s9);
         State s10 = new State("10");
         dfa.addState(s10);
         s10.setAttached("IDENT");
         dfa.addAcceptingState(s10);
         State s11 = new State("11");
         dfa.addState(s11);
         s11.setAttached("IDENT");
         dfa.addAcceptingState(s11);
         State s12 = new State("12");
         dfa.addState(s12);
         s12.setAttached("NUMBER");
         dfa.addAcceptingState(s12);
         State s13 = new State("13");
         dfa.addState(s13);
         s13.setAttached("NUMBER");
         dfa.addAcceptingState(s13);
         State s14 = new State("14");
         dfa.addState(s14);
         s14.setAttached("NUMBER");
         dfa.addAcceptingState(s14);
         State s15 = new State("15");
         dfa.addState(s15);
         s15.setAttached("NUMBER");
         dfa.addAcceptingState(s15);
         State s16 = new State("16");
         dfa.addState(s16);
         s16.setAttached("NUMBER");
         dfa.addAcceptingState(s16);
         State s17 = new State("17");
         dfa.addState(s17);
         s17.setAttached("NUMBER");
         dfa.addAcceptingState(s17);
         State s18 = new State("18");
         dfa.addState(s18);
         s18.setAttached("NUMBER");
         dfa.addAcceptingState(s18);
         State s19 = new State("19");
         dfa.addState(s19);
         s19.setAttached("NUMBER");
         dfa.addAcceptingState(s19);
         State s20 = new State("20");
         dfa.addState(s20);
         s20.setAttached("NUMBER");
         dfa.addAcceptingState(s20);
         State s21 = new State("21");
         dfa.addState(s21);
         s21.setAttached("NUMBER");
         dfa.addAcceptingState(s21);
         State s22 = new State("22");
         dfa.addState(s22);
         s22.setAttached("LPAREN");
         dfa.addAcceptingState(s22);
         State s23 = new State("23");
         dfa.addState(s23);
         s23.setAttached("RPAREN");
         dfa.addAcceptingState(s23);
         State s24 = new State("24");
         dfa.addState(s24);
         s24.setAttached("EQUAL");
         dfa.addAcceptingState(s24);
         State s25 = new State("25");
         dfa.addState(s25);
         s25.setAttached("IGNORE");
         dfa.addAcceptingState(s25);
         State s26 = new State("26");
         dfa.addState(s26);
         s26.setAttached("IGNORE");
         dfa.addAcceptingState(s26);
         State s27 = new State("27");
         dfa.addState(s27);
         s27.setAttached("IGNORE");
         dfa.addAcceptingState(s27);
         State s28 = new State("28");
         dfa.addState(s28);
         s28.setAttached("PLUS");
         dfa.addAcceptingState(s28);
         State s29 = new State("29");
         dfa.addState(s29);
         s29.setAttached("MINUS");
         dfa.addAcceptingState(s29);
         State s30 = new State("30");
         dfa.addState(s30);
         s30.setAttached("SQRBRACKET");
         dfa.addAcceptingState(s30);
         State s31 = new State("31");
         dfa.addState(s31);
         s31.setAttached("SQLBRACKET");
         dfa.addAcceptingState(s31);
         State s32 = new State("32");
         dfa.addState(s32);
         s32.setAttached("CURBRACKET");
         dfa.addAcceptingState(s32);
         State s33 = new State("33");
         dfa.addState(s33);
         s33.setAttached("CULBRACKET");
         dfa.addAcceptingState(s33);
         State s34 = new State("34");
         dfa.addState(s34);
         s34.setAttached("RESERVED");
         dfa.addAcceptingState(s34);
         State s35 = new State("35");
         dfa.addState(s35);
         s35.setAttached("CHAR");
         dfa.addAcceptingState(s35);
         State s36 = new State("36");
         dfa.addState(s36);
         s36.setAttached("RESERVED");
         dfa.addAcceptingState(s36);
         State s37 = new State("37");
         dfa.addState(s37);
         s37.setAttached("RESERVED");
         dfa.addAcceptingState(s37);
         State s38 = new State("38");
         dfa.addState(s38);
         s38.setAttached("STRING");
         dfa.addAcceptingState(s38);
         State s39 = new State("39");
         dfa.addState(s39);
         s39.setAttached("NUMBER");
         dfa.addAcceptingState(s39);
         State s40 = new State("40");
         dfa.addState(s40);
         s40.setAttached("NUMBER");
         dfa.addAcceptingState(s40);
         State s41 = new State("41");
         dfa.addState(s41);
         s41.setAttached("NUMBER");
         dfa.addAcceptingState(s41);
         State s42 = new State("42");
         dfa.addState(s42);
         s42.setAttached("NUMBER");
         dfa.addAcceptingState(s42);
         State s43 = new State("43");
         dfa.addState(s43);
         s43.setAttached("NUMBER");
         dfa.addAcceptingState(s43);
         State s44 = new State("44");
         dfa.addState(s44);
         s44.setAttached("NUMBER");
         dfa.addAcceptingState(s44);
         State s45 = new State("45");
         dfa.addState(s45);
         s45.setAttached("NUMBER");
         dfa.addAcceptingState(s45);
         State s46 = new State("46");
         dfa.addState(s46);
         s46.setAttached("NUMBER");
         dfa.addAcceptingState(s46);
         State s47 = new State("47");
         dfa.addState(s47);
         s47.setAttached("NUMBER");
         dfa.addAcceptingState(s47);
         State s48 = new State("48");
         dfa.addState(s48);
         s48.setAttached("NUMBER");
         dfa.addAcceptingState(s48);
         State s49 = new State("49");
         dfa.addState(s49);
         s49.setAttached("IDENT");
         dfa.addAcceptingState(s49);
         State s50 = new State("50");
         dfa.addState(s50);
         s50.setAttached("IDENT");
         dfa.addAcceptingState(s50);
         State s51 = new State("51");
         dfa.addState(s51);
         s51.setAttached("IDENT");
         dfa.addAcceptingState(s51);
         State s52 = new State("52");
         dfa.addState(s52);
         s52.setAttached("IDENT");
         dfa.addAcceptingState(s52);
         State s53 = new State("53");
         dfa.addState(s53);
         s53.setAttached("IDENT");
         dfa.addAcceptingState(s53);
         State s54 = new State("54");
         dfa.addState(s54);
         s54.setAttached("IDENT");
         dfa.addAcceptingState(s54);
         State s55 = new State("55");
         dfa.addState(s55);
         s55.setAttached("IDENT");
         dfa.addAcceptingState(s55);
         State s56 = new State("56");
         dfa.addState(s56);
         s56.setAttached("IDENT");
         dfa.addAcceptingState(s56);
         State s57 = new State("57");
         dfa.addState(s57);
         s57.setAttached("IDENT");
         dfa.addAcceptingState(s57);
         State s58 = new State("58");
         dfa.addState(s58);
         s58.setAttached("IDENT");
         dfa.addAcceptingState(s58);
         State s59 = new State("59");
         dfa.addState(s59);
         s59.setAttached("IDENT");
         dfa.addAcceptingState(s59);
         State s60 = new State("60");
         dfa.addState(s60);
         s60.setAttached("IDENT");
         dfa.addAcceptingState(s60);
         State s61 = new State("61");
         dfa.addState(s61);
         s61.setAttached("IDENT");
         dfa.addAcceptingState(s61);
         State s62 = new State("62");
         dfa.addState(s62);
         s62.setAttached("IDENT");
         dfa.addAcceptingState(s62);
         State s63 = new State("63");
         dfa.addState(s63);
         s63.setAttached("IDENT");
         dfa.addAcceptingState(s63);
         State s64 = new State("64");
         dfa.addState(s64);
         s64.setAttached("IDENT");
         dfa.addAcceptingState(s64);
         State s65 = new State("65");
         dfa.addState(s65);
         s65.setAttached("IDENT");
         dfa.addAcceptingState(s65);
         State s66 = new State("66");
         dfa.addState(s66);
         s66.setAttached("IDENT");
         dfa.addAcceptingState(s66);
         State s67 = new State("67");
         dfa.addState(s67);
         s67.setAttached("IDENT");
         dfa.addAcceptingState(s67);
         State s68 = new State("68");
         dfa.addState(s68);
         s68.setAttached("IDENT");
         dfa.addAcceptingState(s68);
         State s69 = new State("69");
         dfa.addState(s69);
         s69.setAttached("RESERVED");
         dfa.addAcceptingState(s69);
         State s70 = new State("70");
         dfa.addState(s70);
         s70.setAttached("RESERVED");
         dfa.addAcceptingState(s70);
         State s71 = new State("71");
         dfa.addState(s71);
         s71.setAttached("RESERVED");
         dfa.addAcceptingState(s71);
         State s72 = new State("72");
         dfa.addState(s72);
         State s73 = new State("73");
         dfa.addState(s73);
         State s74 = new State("74");
         dfa.addState(s74);
         State s75 = new State("75");
         dfa.addState(s75);
         State s76 = new State("76");
         dfa.addState(s76);
         State s77 = new State("77");
         dfa.addState(s77);
         State s78 = new State("78");
         dfa.addState(s78);
         State s79 = new State("79");
         dfa.addState(s79);
         State s80 = new State("80");
         dfa.addState(s80);
         State s81 = new State("81");
         dfa.addState(s81);
         State s82 = new State("82");
         dfa.addState(s82);
         State s83 = new State("83");
         dfa.addState(s83);
         State s84 = new State("84");
         dfa.addState(s84);
         State s85 = new State("85");
         dfa.addState(s85);
         State s86 = new State("86");
         dfa.addState(s86);
         State s87 = new State("87");
         dfa.addState(s87);
         State s88 = new State("88");
         dfa.addState(s88);
         State s89 = new State("89");
         dfa.addState(s89);
         State s90 = new State("90");
         dfa.addState(s90);
         State s91 = new State("91");
         dfa.addState(s91);
         State s92 = new State("92");
         dfa.addState(s92);
         State s93 = new State("93");
         dfa.addState(s93);
         State s94 = new State("94");
         dfa.addState(s94);
         State s95 = new State("95");
         dfa.addState(s95);
         State s96 = new State("96");
         dfa.addState(s96);
         State s97 = new State("97");
         dfa.addState(s97);
         State s98 = new State("98");
         dfa.addState(s98);
         State s99 = new State("99");
         dfa.addState(s99);
         State s100 = new State("100");
         dfa.addState(s100);
         State s101 = new State("101");
         dfa.addState(s101);
         State s102 = new State("102");
         dfa.addState(s102);
         State s103 = new State("103");
         dfa.addState(s103);
         State s104 = new State("104");
         dfa.addState(s104);
         State s105 = new State("105");
         dfa.addState(s105);
         State s106 = new State("106");
         dfa.addState(s106);
         State s107 = new State("107");
         dfa.addState(s107);
         State s108 = new State("108");
         dfa.addState(s108);
         State s109 = new State("109");
         dfa.addState(s109);
         State s110 = new State("110");
         dfa.addState(s110);
         State s111 = new State("111");
         dfa.addState(s111);
         State s112 = new State("112");
         dfa.addState(s112);
         State s113 = new State("113");
         dfa.addState(s113);
         State s114 = new State("114");
         dfa.addState(s114);
         State s115 = new State("115");
         dfa.addState(s115);
         State s116 = new State("116");
         dfa.addState(s116);
         State s117 = new State("117");
         dfa.addState(s117);
         State s118 = new State("118");
         dfa.addState(s118);
         State s119 = new State("119");
         dfa.addState(s119);
         State s120 = new State("120");
         dfa.addState(s120);
         State s121 = new State("121");
         dfa.addState(s121);
         State s122 = new State("122");
         dfa.addState(s122);
         State s123 = new State("123");
         dfa.addState(s123);
         State s124 = new State("124");
         dfa.addState(s124);
         State s125 = new State("125");
         dfa.addState(s125);
         State s126 = new State("126");
         dfa.addState(s126);
         dfa.addTransition(new Pair(s1, new Symbol((char)949)), s1);
         dfa.addTransition(new Pair(s1, new Symbol((char)65)), s2);
         dfa.addTransition(new Pair(s1, new Symbol((char)66)), s3);
         dfa.addTransition(new Pair(s1, new Symbol((char)67)), s4);
         dfa.addTransition(new Pair(s1, new Symbol((char)68)), s5);
         dfa.addTransition(new Pair(s1, new Symbol((char)69)), s6);
         dfa.addTransition(new Pair(s1, new Symbol((char)97)), s7);
         dfa.addTransition(new Pair(s1, new Symbol((char)98)), s8);
         dfa.addTransition(new Pair(s1, new Symbol((char)99)), s9);
         dfa.addTransition(new Pair(s1, new Symbol((char)100)), s10);
         dfa.addTransition(new Pair(s1, new Symbol((char)101)), s11);
         dfa.addTransition(new Pair(s1, new Symbol((char)48)), s12);
         dfa.addTransition(new Pair(s1, new Symbol((char)49)), s13);
         dfa.addTransition(new Pair(s1, new Symbol((char)50)), s14);
         dfa.addTransition(new Pair(s1, new Symbol((char)51)), s15);
         dfa.addTransition(new Pair(s1, new Symbol((char)52)), s16);
         dfa.addTransition(new Pair(s1, new Symbol((char)53)), s17);
         dfa.addTransition(new Pair(s1, new Symbol((char)54)), s18);
         dfa.addTransition(new Pair(s1, new Symbol((char)55)), s19);
         dfa.addTransition(new Pair(s1, new Symbol((char)56)), s20);
         dfa.addTransition(new Pair(s1, new Symbol((char)57)), s21);
         dfa.addTransition(new Pair(s1, new Symbol((char)34)), s72);
         dfa.addTransition(new Pair(s1, new Symbol((char)73)), s73);
         dfa.addTransition(new Pair(s1, new Symbol((char)75)), s74);
         dfa.addTransition(new Pair(s1, new Symbol((char)39)), s75);
         dfa.addTransition(new Pair(s1, new Symbol((char)84)), s76);
         dfa.addTransition(new Pair(s1, new Symbol((char)40)), s22);
         dfa.addTransition(new Pair(s1, new Symbol((char)41)), s23);
         dfa.addTransition(new Pair(s1, new Symbol((char)61)), s24);
         dfa.addTransition(new Pair(s1, new Symbol((char)32)), s25);
         dfa.addTransition(new Pair(s1, new Symbol((char)10)), s26);
         dfa.addTransition(new Pair(s1, new Symbol((char)13)), s27);
         dfa.addTransition(new Pair(s1, new Symbol((char)43)), s28);
         dfa.addTransition(new Pair(s1, new Symbol((char)45)), s29);
         dfa.addTransition(new Pair(s1, new Symbol((char)93)), s30);
         dfa.addTransition(new Pair(s1, new Symbol((char)91)), s31);
         dfa.addTransition(new Pair(s1, new Symbol((char)125)), s32);
         dfa.addTransition(new Pair(s1, new Symbol((char)123)), s33);
         dfa.addTransition(new Pair(s33, new Symbol((char)949)), s33);
         dfa.addTransition(new Pair(s32, new Symbol((char)949)), s32);
         dfa.addTransition(new Pair(s31, new Symbol((char)949)), s31);
         dfa.addTransition(new Pair(s30, new Symbol((char)949)), s30);
         dfa.addTransition(new Pair(s29, new Symbol((char)949)), s29);
         dfa.addTransition(new Pair(s28, new Symbol((char)949)), s28);
         dfa.addTransition(new Pair(s27, new Symbol((char)949)), s27);
         dfa.addTransition(new Pair(s26, new Symbol((char)949)), s26);
         dfa.addTransition(new Pair(s25, new Symbol((char)949)), s25);
         dfa.addTransition(new Pair(s24, new Symbol((char)949)), s24);
         dfa.addTransition(new Pair(s23, new Symbol((char)949)), s23);
         dfa.addTransition(new Pair(s22, new Symbol((char)949)), s22);
         dfa.addTransition(new Pair(s76, new Symbol((char)949)), s76);
         dfa.addTransition(new Pair(s76, new Symbol((char)79)), s77);
         dfa.addTransition(new Pair(s77, new Symbol((char)949)), s77);
         dfa.addTransition(new Pair(s77, new Symbol((char)75)), s78);
         dfa.addTransition(new Pair(s78, new Symbol((char)949)), s78);
         dfa.addTransition(new Pair(s78, new Symbol((char)69)), s79);
         dfa.addTransition(new Pair(s79, new Symbol((char)949)), s79);
         dfa.addTransition(new Pair(s79, new Symbol((char)78)), s80);
         dfa.addTransition(new Pair(s80, new Symbol((char)949)), s80);
         dfa.addTransition(new Pair(s80, new Symbol((char)83)), s34);
         dfa.addTransition(new Pair(s34, new Symbol((char)949)), s34);
         dfa.addTransition(new Pair(s75, new Symbol((char)949)), s75);
         dfa.addTransition(new Pair(s75, new Symbol((char)65)), s81);
         dfa.addTransition(new Pair(s75, new Symbol((char)66)), s82);
         dfa.addTransition(new Pair(s75, new Symbol((char)67)), s83);
         dfa.addTransition(new Pair(s75, new Symbol((char)68)), s84);
         dfa.addTransition(new Pair(s75, new Symbol((char)69)), s85);
         dfa.addTransition(new Pair(s75, new Symbol((char)70)), s86);
         dfa.addTransition(new Pair(s75, new Symbol((char)71)), s87);
         dfa.addTransition(new Pair(s75, new Symbol((char)72)), s88);
         dfa.addTransition(new Pair(s75, new Symbol((char)73)), s89);
         dfa.addTransition(new Pair(s75, new Symbol((char)74)), s90);
         dfa.addTransition(new Pair(s75, new Symbol((char)75)), s91);
         dfa.addTransition(new Pair(s91, new Symbol((char)949)), s91);
         dfa.addTransition(new Pair(s91, new Symbol((char)39)), s35);
         dfa.addTransition(new Pair(s35, new Symbol((char)949)), s35);
         dfa.addTransition(new Pair(s90, new Symbol((char)949)), s90);
         dfa.addTransition(new Pair(s90, new Symbol((char)39)), s35);
         dfa.addTransition(new Pair(s89, new Symbol((char)949)), s89);
         dfa.addTransition(new Pair(s89, new Symbol((char)39)), s35);
         dfa.addTransition(new Pair(s88, new Symbol((char)949)), s88);
         dfa.addTransition(new Pair(s88, new Symbol((char)39)), s35);
         dfa.addTransition(new Pair(s87, new Symbol((char)949)), s87);
         dfa.addTransition(new Pair(s87, new Symbol((char)39)), s35);
         dfa.addTransition(new Pair(s86, new Symbol((char)949)), s86);
         dfa.addTransition(new Pair(s86, new Symbol((char)39)), s35);
         dfa.addTransition(new Pair(s85, new Symbol((char)949)), s85);
         dfa.addTransition(new Pair(s85, new Symbol((char)39)), s35);
         dfa.addTransition(new Pair(s84, new Symbol((char)949)), s84);
         dfa.addTransition(new Pair(s84, new Symbol((char)39)), s35);
         dfa.addTransition(new Pair(s83, new Symbol((char)949)), s83);
         dfa.addTransition(new Pair(s83, new Symbol((char)39)), s35);
         dfa.addTransition(new Pair(s82, new Symbol((char)949)), s82);
         dfa.addTransition(new Pair(s82, new Symbol((char)39)), s35);
         dfa.addTransition(new Pair(s81, new Symbol((char)949)), s81);
         dfa.addTransition(new Pair(s81, new Symbol((char)39)), s35);
         dfa.addTransition(new Pair(s74, new Symbol((char)949)), s74);
         dfa.addTransition(new Pair(s74, new Symbol((char)69)), s92);
         dfa.addTransition(new Pair(s92, new Symbol((char)949)), s92);
         dfa.addTransition(new Pair(s92, new Symbol((char)89)), s93);
         dfa.addTransition(new Pair(s93, new Symbol((char)949)), s93);
         dfa.addTransition(new Pair(s93, new Symbol((char)87)), s94);
         dfa.addTransition(new Pair(s94, new Symbol((char)949)), s94);
         dfa.addTransition(new Pair(s94, new Symbol((char)79)), s95);
         dfa.addTransition(new Pair(s95, new Symbol((char)949)), s95);
         dfa.addTransition(new Pair(s95, new Symbol((char)82)), s96);
         dfa.addTransition(new Pair(s96, new Symbol((char)949)), s96);
         dfa.addTransition(new Pair(s96, new Symbol((char)68)), s97);
         dfa.addTransition(new Pair(s97, new Symbol((char)949)), s97);
         dfa.addTransition(new Pair(s97, new Symbol((char)83)), s36);
         dfa.addTransition(new Pair(s36, new Symbol((char)949)), s36);
         dfa.addTransition(new Pair(s73, new Symbol((char)949)), s73);
         dfa.addTransition(new Pair(s73, new Symbol((char)71)), s98);
         dfa.addTransition(new Pair(s98, new Symbol((char)949)), s98);
         dfa.addTransition(new Pair(s98, new Symbol((char)78)), s99);
         dfa.addTransition(new Pair(s99, new Symbol((char)949)), s99);
         dfa.addTransition(new Pair(s99, new Symbol((char)79)), s100);
         dfa.addTransition(new Pair(s100, new Symbol((char)949)), s100);
         dfa.addTransition(new Pair(s100, new Symbol((char)82)), s101);
         dfa.addTransition(new Pair(s101, new Symbol((char)949)), s101);
         dfa.addTransition(new Pair(s101, new Symbol((char)69)), s37);
         dfa.addTransition(new Pair(s37, new Symbol((char)949)), s37);
         dfa.addTransition(new Pair(s72, new Symbol((char)949)), s72);
         dfa.addTransition(new Pair(s72, new Symbol((char)65)), s102);
         dfa.addTransition(new Pair(s72, new Symbol((char)66)), s103);
         dfa.addTransition(new Pair(s72, new Symbol((char)67)), s104);
         dfa.addTransition(new Pair(s72, new Symbol((char)68)), s105);
         dfa.addTransition(new Pair(s72, new Symbol((char)69)), s106);
         dfa.addTransition(new Pair(s72, new Symbol((char)34)), s38);
         dfa.addTransition(new Pair(s72, new Symbol((char)70)), s107);
         dfa.addTransition(new Pair(s72, new Symbol((char)71)), s108);
         dfa.addTransition(new Pair(s72, new Symbol((char)72)), s109);
         dfa.addTransition(new Pair(s72, new Symbol((char)73)), s110);
         dfa.addTransition(new Pair(s72, new Symbol((char)74)), s111);
         dfa.addTransition(new Pair(s72, new Symbol((char)75)), s112);
         dfa.addTransition(new Pair(s112, new Symbol((char)949)), s112);
         dfa.addTransition(new Pair(s112, new Symbol((char)65)), s102);
         dfa.addTransition(new Pair(s112, new Symbol((char)66)), s103);
         dfa.addTransition(new Pair(s112, new Symbol((char)67)), s104);
         dfa.addTransition(new Pair(s112, new Symbol((char)68)), s105);
         dfa.addTransition(new Pair(s112, new Symbol((char)69)), s106);
         dfa.addTransition(new Pair(s112, new Symbol((char)34)), s38);
         dfa.addTransition(new Pair(s112, new Symbol((char)70)), s107);
         dfa.addTransition(new Pair(s112, new Symbol((char)71)), s108);
         dfa.addTransition(new Pair(s112, new Symbol((char)72)), s109);
         dfa.addTransition(new Pair(s112, new Symbol((char)73)), s110);
         dfa.addTransition(new Pair(s112, new Symbol((char)74)), s111);
         dfa.addTransition(new Pair(s112, new Symbol((char)75)), s112);
         dfa.addTransition(new Pair(s111, new Symbol((char)949)), s111);
         dfa.addTransition(new Pair(s111, new Symbol((char)65)), s102);
         dfa.addTransition(new Pair(s111, new Symbol((char)66)), s103);
         dfa.addTransition(new Pair(s111, new Symbol((char)67)), s104);
         dfa.addTransition(new Pair(s111, new Symbol((char)68)), s105);
         dfa.addTransition(new Pair(s111, new Symbol((char)69)), s106);
         dfa.addTransition(new Pair(s111, new Symbol((char)34)), s38);
         dfa.addTransition(new Pair(s111, new Symbol((char)70)), s107);
         dfa.addTransition(new Pair(s111, new Symbol((char)71)), s108);
         dfa.addTransition(new Pair(s111, new Symbol((char)72)), s109);
         dfa.addTransition(new Pair(s111, new Symbol((char)73)), s110);
         dfa.addTransition(new Pair(s111, new Symbol((char)74)), s111);
         dfa.addTransition(new Pair(s111, new Symbol((char)75)), s112);
         dfa.addTransition(new Pair(s110, new Symbol((char)949)), s110);
         dfa.addTransition(new Pair(s110, new Symbol((char)65)), s102);
         dfa.addTransition(new Pair(s110, new Symbol((char)66)), s103);
         dfa.addTransition(new Pair(s110, new Symbol((char)67)), s104);
         dfa.addTransition(new Pair(s110, new Symbol((char)68)), s105);
         dfa.addTransition(new Pair(s110, new Symbol((char)69)), s106);
         dfa.addTransition(new Pair(s110, new Symbol((char)34)), s38);
         dfa.addTransition(new Pair(s110, new Symbol((char)70)), s107);
         dfa.addTransition(new Pair(s110, new Symbol((char)71)), s108);
         dfa.addTransition(new Pair(s110, new Symbol((char)72)), s109);
         dfa.addTransition(new Pair(s110, new Symbol((char)73)), s110);
         dfa.addTransition(new Pair(s110, new Symbol((char)74)), s111);
         dfa.addTransition(new Pair(s110, new Symbol((char)75)), s112);
         dfa.addTransition(new Pair(s109, new Symbol((char)949)), s109);
         dfa.addTransition(new Pair(s109, new Symbol((char)65)), s102);
         dfa.addTransition(new Pair(s109, new Symbol((char)66)), s103);
         dfa.addTransition(new Pair(s109, new Symbol((char)67)), s104);
         dfa.addTransition(new Pair(s109, new Symbol((char)68)), s105);
         dfa.addTransition(new Pair(s109, new Symbol((char)69)), s106);
         dfa.addTransition(new Pair(s109, new Symbol((char)34)), s38);
         dfa.addTransition(new Pair(s109, new Symbol((char)70)), s107);
         dfa.addTransition(new Pair(s109, new Symbol((char)71)), s108);
         dfa.addTransition(new Pair(s109, new Symbol((char)72)), s109);
         dfa.addTransition(new Pair(s109, new Symbol((char)73)), s110);
         dfa.addTransition(new Pair(s109, new Symbol((char)74)), s111);
         dfa.addTransition(new Pair(s109, new Symbol((char)75)), s112);
         dfa.addTransition(new Pair(s108, new Symbol((char)949)), s108);
         dfa.addTransition(new Pair(s108, new Symbol((char)65)), s102);
         dfa.addTransition(new Pair(s108, new Symbol((char)66)), s103);
         dfa.addTransition(new Pair(s108, new Symbol((char)67)), s104);
         dfa.addTransition(new Pair(s108, new Symbol((char)68)), s105);
         dfa.addTransition(new Pair(s108, new Symbol((char)69)), s106);
         dfa.addTransition(new Pair(s108, new Symbol((char)34)), s38);
         dfa.addTransition(new Pair(s108, new Symbol((char)70)), s107);
         dfa.addTransition(new Pair(s108, new Symbol((char)71)), s108);
         dfa.addTransition(new Pair(s108, new Symbol((char)72)), s109);
         dfa.addTransition(new Pair(s108, new Symbol((char)73)), s110);
         dfa.addTransition(new Pair(s108, new Symbol((char)74)), s111);
         dfa.addTransition(new Pair(s108, new Symbol((char)75)), s112);
         dfa.addTransition(new Pair(s107, new Symbol((char)949)), s107);
         dfa.addTransition(new Pair(s107, new Symbol((char)65)), s102);
         dfa.addTransition(new Pair(s107, new Symbol((char)66)), s103);
         dfa.addTransition(new Pair(s107, new Symbol((char)67)), s104);
         dfa.addTransition(new Pair(s107, new Symbol((char)68)), s105);
         dfa.addTransition(new Pair(s107, new Symbol((char)69)), s106);
         dfa.addTransition(new Pair(s107, new Symbol((char)34)), s38);
         dfa.addTransition(new Pair(s107, new Symbol((char)70)), s107);
         dfa.addTransition(new Pair(s107, new Symbol((char)71)), s108);
         dfa.addTransition(new Pair(s107, new Symbol((char)72)), s109);
         dfa.addTransition(new Pair(s107, new Symbol((char)73)), s110);
         dfa.addTransition(new Pair(s107, new Symbol((char)74)), s111);
         dfa.addTransition(new Pair(s107, new Symbol((char)75)), s112);
         dfa.addTransition(new Pair(s38, new Symbol((char)949)), s38);
         dfa.addTransition(new Pair(s106, new Symbol((char)949)), s106);
         dfa.addTransition(new Pair(s106, new Symbol((char)65)), s102);
         dfa.addTransition(new Pair(s106, new Symbol((char)66)), s103);
         dfa.addTransition(new Pair(s106, new Symbol((char)67)), s104);
         dfa.addTransition(new Pair(s106, new Symbol((char)68)), s105);
         dfa.addTransition(new Pair(s106, new Symbol((char)69)), s106);
         dfa.addTransition(new Pair(s106, new Symbol((char)34)), s38);
         dfa.addTransition(new Pair(s106, new Symbol((char)70)), s107);
         dfa.addTransition(new Pair(s106, new Symbol((char)71)), s108);
         dfa.addTransition(new Pair(s106, new Symbol((char)72)), s109);
         dfa.addTransition(new Pair(s106, new Symbol((char)73)), s110);
         dfa.addTransition(new Pair(s106, new Symbol((char)74)), s111);
         dfa.addTransition(new Pair(s106, new Symbol((char)75)), s112);
         dfa.addTransition(new Pair(s105, new Symbol((char)949)), s105);
         dfa.addTransition(new Pair(s105, new Symbol((char)65)), s102);
         dfa.addTransition(new Pair(s105, new Symbol((char)66)), s103);
         dfa.addTransition(new Pair(s105, new Symbol((char)67)), s104);
         dfa.addTransition(new Pair(s105, new Symbol((char)68)), s105);
         dfa.addTransition(new Pair(s105, new Symbol((char)69)), s106);
         dfa.addTransition(new Pair(s105, new Symbol((char)34)), s38);
         dfa.addTransition(new Pair(s105, new Symbol((char)70)), s107);
         dfa.addTransition(new Pair(s105, new Symbol((char)71)), s108);
         dfa.addTransition(new Pair(s105, new Symbol((char)72)), s109);
         dfa.addTransition(new Pair(s105, new Symbol((char)73)), s110);
         dfa.addTransition(new Pair(s105, new Symbol((char)74)), s111);
         dfa.addTransition(new Pair(s105, new Symbol((char)75)), s112);
         dfa.addTransition(new Pair(s104, new Symbol((char)949)), s104);
         dfa.addTransition(new Pair(s104, new Symbol((char)65)), s102);
         dfa.addTransition(new Pair(s104, new Symbol((char)66)), s103);
         dfa.addTransition(new Pair(s104, new Symbol((char)67)), s104);
         dfa.addTransition(new Pair(s104, new Symbol((char)68)), s105);
         dfa.addTransition(new Pair(s104, new Symbol((char)69)), s106);
         dfa.addTransition(new Pair(s104, new Symbol((char)34)), s38);
         dfa.addTransition(new Pair(s104, new Symbol((char)70)), s107);
         dfa.addTransition(new Pair(s104, new Symbol((char)71)), s108);
         dfa.addTransition(new Pair(s104, new Symbol((char)72)), s109);
         dfa.addTransition(new Pair(s104, new Symbol((char)73)), s110);
         dfa.addTransition(new Pair(s104, new Symbol((char)74)), s111);
         dfa.addTransition(new Pair(s104, new Symbol((char)75)), s112);
         dfa.addTransition(new Pair(s103, new Symbol((char)949)), s103);
         dfa.addTransition(new Pair(s103, new Symbol((char)65)), s102);
         dfa.addTransition(new Pair(s103, new Symbol((char)66)), s103);
         dfa.addTransition(new Pair(s103, new Symbol((char)67)), s104);
         dfa.addTransition(new Pair(s103, new Symbol((char)68)), s105);
         dfa.addTransition(new Pair(s103, new Symbol((char)69)), s106);
         dfa.addTransition(new Pair(s103, new Symbol((char)34)), s38);
         dfa.addTransition(new Pair(s103, new Symbol((char)70)), s107);
         dfa.addTransition(new Pair(s103, new Symbol((char)71)), s108);
         dfa.addTransition(new Pair(s103, new Symbol((char)72)), s109);
         dfa.addTransition(new Pair(s103, new Symbol((char)73)), s110);
         dfa.addTransition(new Pair(s103, new Symbol((char)74)), s111);
         dfa.addTransition(new Pair(s103, new Symbol((char)75)), s112);
         dfa.addTransition(new Pair(s102, new Symbol((char)949)), s102);
         dfa.addTransition(new Pair(s102, new Symbol((char)65)), s102);
         dfa.addTransition(new Pair(s102, new Symbol((char)66)), s103);
         dfa.addTransition(new Pair(s102, new Symbol((char)67)), s104);
         dfa.addTransition(new Pair(s102, new Symbol((char)68)), s105);
         dfa.addTransition(new Pair(s102, new Symbol((char)69)), s106);
         dfa.addTransition(new Pair(s102, new Symbol((char)34)), s38);
         dfa.addTransition(new Pair(s102, new Symbol((char)70)), s107);
         dfa.addTransition(new Pair(s102, new Symbol((char)71)), s108);
         dfa.addTransition(new Pair(s102, new Symbol((char)72)), s109);
         dfa.addTransition(new Pair(s102, new Symbol((char)73)), s110);
         dfa.addTransition(new Pair(s102, new Symbol((char)74)), s111);
         dfa.addTransition(new Pair(s102, new Symbol((char)75)), s112);
         dfa.addTransition(new Pair(s21, new Symbol((char)949)), s21);
         dfa.addTransition(new Pair(s21, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s21, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s21, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s21, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s21, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s21, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s21, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s21, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s21, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s21, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s48, new Symbol((char)949)), s48);
         dfa.addTransition(new Pair(s48, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s48, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s48, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s48, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s48, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s48, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s48, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s48, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s48, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s48, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s47, new Symbol((char)949)), s47);
         dfa.addTransition(new Pair(s47, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s47, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s47, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s47, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s47, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s47, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s47, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s47, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s47, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s47, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s46, new Symbol((char)949)), s46);
         dfa.addTransition(new Pair(s46, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s46, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s46, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s46, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s46, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s46, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s46, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s46, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s46, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s46, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s45, new Symbol((char)949)), s45);
         dfa.addTransition(new Pair(s45, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s45, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s45, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s45, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s45, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s45, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s45, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s45, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s45, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s45, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s44, new Symbol((char)949)), s44);
         dfa.addTransition(new Pair(s44, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s44, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s44, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s44, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s44, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s44, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s44, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s44, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s44, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s44, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s43, new Symbol((char)949)), s43);
         dfa.addTransition(new Pair(s43, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s43, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s43, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s43, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s43, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s43, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s43, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s43, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s43, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s43, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s42, new Symbol((char)949)), s42);
         dfa.addTransition(new Pair(s42, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s42, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s42, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s42, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s42, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s42, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s42, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s42, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s42, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s42, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s41, new Symbol((char)949)), s41);
         dfa.addTransition(new Pair(s41, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s41, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s41, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s41, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s41, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s41, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s41, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s41, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s41, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s41, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s40, new Symbol((char)949)), s40);
         dfa.addTransition(new Pair(s40, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s40, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s40, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s40, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s40, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s40, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s40, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s40, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s40, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s40, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s39, new Symbol((char)949)), s39);
         dfa.addTransition(new Pair(s39, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s39, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s39, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s39, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s39, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s39, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s39, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s39, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s39, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s39, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s20, new Symbol((char)949)), s20);
         dfa.addTransition(new Pair(s20, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s20, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s20, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s20, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s20, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s20, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s20, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s20, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s20, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s20, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s19, new Symbol((char)949)), s19);
         dfa.addTransition(new Pair(s19, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s19, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s19, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s19, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s19, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s19, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s19, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s19, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s19, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s19, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s18, new Symbol((char)949)), s18);
         dfa.addTransition(new Pair(s18, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s18, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s18, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s18, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s18, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s18, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s18, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s18, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s18, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s18, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s17, new Symbol((char)949)), s17);
         dfa.addTransition(new Pair(s17, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s17, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s17, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s17, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s17, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s17, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s17, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s17, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s17, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s17, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s16, new Symbol((char)949)), s16);
         dfa.addTransition(new Pair(s16, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s16, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s16, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s16, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s16, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s16, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s16, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s16, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s16, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s16, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s15, new Symbol((char)949)), s15);
         dfa.addTransition(new Pair(s15, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s15, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s15, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s15, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s15, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s15, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s15, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s15, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s15, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s15, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s14, new Symbol((char)949)), s14);
         dfa.addTransition(new Pair(s14, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s14, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s14, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s14, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s14, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s14, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s14, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s14, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s14, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s14, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s13, new Symbol((char)949)), s13);
         dfa.addTransition(new Pair(s13, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s13, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s13, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s13, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s13, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s13, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s13, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s13, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s13, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s13, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s12, new Symbol((char)949)), s12);
         dfa.addTransition(new Pair(s12, new Symbol((char)48)), s39);
         dfa.addTransition(new Pair(s12, new Symbol((char)49)), s40);
         dfa.addTransition(new Pair(s12, new Symbol((char)50)), s41);
         dfa.addTransition(new Pair(s12, new Symbol((char)51)), s42);
         dfa.addTransition(new Pair(s12, new Symbol((char)52)), s43);
         dfa.addTransition(new Pair(s12, new Symbol((char)53)), s44);
         dfa.addTransition(new Pair(s12, new Symbol((char)54)), s45);
         dfa.addTransition(new Pair(s12, new Symbol((char)55)), s46);
         dfa.addTransition(new Pair(s12, new Symbol((char)56)), s47);
         dfa.addTransition(new Pair(s12, new Symbol((char)57)), s48);
         dfa.addTransition(new Pair(s11, new Symbol((char)949)), s11);
         dfa.addTransition(new Pair(s11, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s11, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s11, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s11, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s11, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s11, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s11, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s11, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s11, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s11, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s11, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s11, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s11, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s11, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s11, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s11, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s11, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s11, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s11, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s11, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s68, new Symbol((char)949)), s68);
         dfa.addTransition(new Pair(s68, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s68, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s68, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s68, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s68, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s68, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s68, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s68, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s68, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s68, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s68, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s68, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s68, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s68, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s68, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s68, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s68, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s68, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s68, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s68, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s67, new Symbol((char)949)), s67);
         dfa.addTransition(new Pair(s67, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s67, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s67, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s67, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s67, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s67, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s67, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s67, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s67, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s67, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s67, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s67, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s67, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s67, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s67, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s67, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s67, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s67, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s67, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s67, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s66, new Symbol((char)949)), s66);
         dfa.addTransition(new Pair(s66, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s66, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s66, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s66, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s66, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s66, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s66, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s66, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s66, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s66, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s66, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s66, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s66, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s66, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s66, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s66, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s66, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s66, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s66, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s66, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s65, new Symbol((char)949)), s65);
         dfa.addTransition(new Pair(s65, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s65, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s65, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s65, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s65, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s65, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s65, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s65, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s65, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s65, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s65, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s65, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s65, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s65, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s65, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s65, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s65, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s65, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s65, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s65, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s64, new Symbol((char)949)), s64);
         dfa.addTransition(new Pair(s64, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s64, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s64, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s64, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s64, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s64, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s64, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s64, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s64, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s64, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s64, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s64, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s64, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s64, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s64, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s64, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s64, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s64, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s64, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s64, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s63, new Symbol((char)949)), s63);
         dfa.addTransition(new Pair(s63, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s63, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s63, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s63, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s63, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s63, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s63, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s63, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s63, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s63, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s63, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s63, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s63, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s63, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s63, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s63, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s63, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s63, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s63, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s63, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s62, new Symbol((char)949)), s62);
         dfa.addTransition(new Pair(s62, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s62, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s62, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s62, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s62, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s62, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s62, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s62, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s62, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s62, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s62, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s62, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s62, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s62, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s62, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s62, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s62, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s62, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s62, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s62, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s61, new Symbol((char)949)), s61);
         dfa.addTransition(new Pair(s61, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s61, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s61, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s61, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s61, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s61, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s61, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s61, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s61, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s61, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s61, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s61, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s61, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s61, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s61, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s61, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s61, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s61, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s61, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s61, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s60, new Symbol((char)949)), s60);
         dfa.addTransition(new Pair(s60, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s60, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s60, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s60, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s60, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s60, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s60, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s60, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s60, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s60, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s60, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s60, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s60, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s60, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s60, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s60, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s60, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s60, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s60, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s60, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s59, new Symbol((char)949)), s59);
         dfa.addTransition(new Pair(s59, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s59, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s59, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s59, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s59, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s59, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s59, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s59, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s59, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s59, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s59, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s59, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s59, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s59, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s59, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s59, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s59, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s59, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s59, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s59, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s58, new Symbol((char)949)), s58);
         dfa.addTransition(new Pair(s58, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s58, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s58, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s58, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s58, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s58, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s58, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s58, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s58, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s58, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s58, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s58, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s58, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s58, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s58, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s58, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s58, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s58, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s58, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s58, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s57, new Symbol((char)949)), s57);
         dfa.addTransition(new Pair(s57, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s57, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s57, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s57, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s57, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s57, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s57, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s57, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s57, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s57, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s57, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s57, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s57, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s57, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s57, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s57, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s57, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s57, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s57, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s57, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s56, new Symbol((char)949)), s56);
         dfa.addTransition(new Pair(s56, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s56, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s56, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s56, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s56, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s56, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s56, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s56, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s56, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s56, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s56, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s56, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s56, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s56, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s56, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s56, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s56, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s56, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s56, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s56, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s55, new Symbol((char)949)), s55);
         dfa.addTransition(new Pair(s55, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s55, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s55, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s55, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s55, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s55, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s55, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s55, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s55, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s55, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s55, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s55, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s55, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s55, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s55, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s55, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s55, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s55, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s55, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s55, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s54, new Symbol((char)949)), s54);
         dfa.addTransition(new Pair(s54, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s54, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s54, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s54, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s54, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s54, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s54, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s54, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s54, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s54, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s54, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s54, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s54, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s54, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s54, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s54, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s54, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s54, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s54, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s54, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s53, new Symbol((char)949)), s53);
         dfa.addTransition(new Pair(s53, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s53, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s53, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s53, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s53, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s53, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s53, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s53, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s53, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s53, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s53, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s53, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s53, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s53, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s53, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s53, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s53, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s53, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s53, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s53, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s52, new Symbol((char)949)), s52);
         dfa.addTransition(new Pair(s52, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s52, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s52, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s52, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s52, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s52, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s52, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s52, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s52, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s52, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s52, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s52, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s52, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s52, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s52, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s52, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s52, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s52, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s52, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s52, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s51, new Symbol((char)949)), s51);
         dfa.addTransition(new Pair(s51, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s51, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s51, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s51, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s51, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s51, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s51, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s51, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s51, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s51, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s51, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s51, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s51, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s51, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s51, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s51, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s51, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s51, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s51, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s51, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s50, new Symbol((char)949)), s50);
         dfa.addTransition(new Pair(s50, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s50, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s50, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s50, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s50, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s50, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s50, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s50, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s50, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s50, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s50, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s50, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s50, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s50, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s50, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s50, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s50, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s50, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s50, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s50, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s49, new Symbol((char)949)), s49);
         dfa.addTransition(new Pair(s49, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s49, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s49, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s49, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s49, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s49, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s49, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s49, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s49, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s49, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s49, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s49, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s49, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s49, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s49, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s49, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s49, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s49, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s49, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s49, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s10, new Symbol((char)949)), s10);
         dfa.addTransition(new Pair(s10, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s10, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s10, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s10, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s10, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s10, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s10, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s10, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s10, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s10, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s10, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s10, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s10, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s10, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s10, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s10, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s10, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s10, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s10, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s10, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s9, new Symbol((char)949)), s9);
         dfa.addTransition(new Pair(s9, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s9, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s9, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s9, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s9, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s9, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s9, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s9, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s9, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s9, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s9, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s9, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s9, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s9, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s9, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s9, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s9, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s9, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s9, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s9, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s8, new Symbol((char)949)), s8);
         dfa.addTransition(new Pair(s8, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s8, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s8, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s8, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s8, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s8, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s8, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s8, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s8, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s8, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s8, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s8, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s8, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s8, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s8, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s8, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s8, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s8, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s8, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s8, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s7, new Symbol((char)949)), s7);
         dfa.addTransition(new Pair(s7, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s7, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s7, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s7, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s7, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s7, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s7, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s7, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s7, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s7, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s7, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s7, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s7, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s7, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s7, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s7, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s7, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s7, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s7, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s7, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s6, new Symbol((char)949)), s6);
         dfa.addTransition(new Pair(s6, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s6, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s6, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s6, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s6, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s6, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s6, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s6, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s6, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s6, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s6, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s6, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s6, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s6, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s6, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s6, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s6, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s6, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s6, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s6, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s5, new Symbol((char)949)), s5);
         dfa.addTransition(new Pair(s5, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s5, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s5, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s5, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s5, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s5, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s5, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s5, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s5, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s5, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s5, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s5, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s5, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s5, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s5, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s5, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s5, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s5, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s5, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s5, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s4, new Symbol((char)949)), s4);
         dfa.addTransition(new Pair(s4, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s4, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s4, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s4, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s4, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s4, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s4, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s4, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s4, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s4, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s4, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s4, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s4, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s4, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s4, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s4, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s4, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s4, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s4, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s4, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s4, new Symbol((char)72)), s113);
         dfa.addTransition(new Pair(s4, new Symbol((char)79)), s114);
         dfa.addTransition(new Pair(s114, new Symbol((char)949)), s114);
         dfa.addTransition(new Pair(s114, new Symbol((char)77)), s115);
         dfa.addTransition(new Pair(s115, new Symbol((char)949)), s115);
         dfa.addTransition(new Pair(s115, new Symbol((char)80)), s116);
         dfa.addTransition(new Pair(s116, new Symbol((char)949)), s116);
         dfa.addTransition(new Pair(s116, new Symbol((char)73)), s117);
         dfa.addTransition(new Pair(s117, new Symbol((char)949)), s117);
         dfa.addTransition(new Pair(s117, new Symbol((char)76)), s118);
         dfa.addTransition(new Pair(s118, new Symbol((char)949)), s118);
         dfa.addTransition(new Pair(s118, new Symbol((char)69)), s119);
         dfa.addTransition(new Pair(s119, new Symbol((char)949)), s119);
         dfa.addTransition(new Pair(s119, new Symbol((char)82)), s69);
         dfa.addTransition(new Pair(s69, new Symbol((char)949)), s69);
         dfa.addTransition(new Pair(s113, new Symbol((char)949)), s113);
         dfa.addTransition(new Pair(s113, new Symbol((char)65)), s120);
         dfa.addTransition(new Pair(s113, new Symbol((char)82)), s70);
         dfa.addTransition(new Pair(s70, new Symbol((char)949)), s70);
         dfa.addTransition(new Pair(s120, new Symbol((char)949)), s120);
         dfa.addTransition(new Pair(s120, new Symbol((char)82)), s121);
         dfa.addTransition(new Pair(s121, new Symbol((char)949)), s121);
         dfa.addTransition(new Pair(s121, new Symbol((char)65)), s122);
         dfa.addTransition(new Pair(s122, new Symbol((char)949)), s122);
         dfa.addTransition(new Pair(s122, new Symbol((char)67)), s123);
         dfa.addTransition(new Pair(s123, new Symbol((char)949)), s123);
         dfa.addTransition(new Pair(s123, new Symbol((char)84)), s124);
         dfa.addTransition(new Pair(s124, new Symbol((char)949)), s124);
         dfa.addTransition(new Pair(s124, new Symbol((char)69)), s125);
         dfa.addTransition(new Pair(s125, new Symbol((char)949)), s125);
         dfa.addTransition(new Pair(s125, new Symbol((char)82)), s126);
         dfa.addTransition(new Pair(s126, new Symbol((char)949)), s126);
         dfa.addTransition(new Pair(s126, new Symbol((char)83)), s71);
         dfa.addTransition(new Pair(s71, new Symbol((char)949)), s71);
         dfa.addTransition(new Pair(s3, new Symbol((char)949)), s3);
         dfa.addTransition(new Pair(s3, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s3, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s3, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s3, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s3, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s3, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s3, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s3, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s3, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s3, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s3, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s3, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s3, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s3, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s3, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s3, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s3, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s3, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s3, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s3, new Symbol((char)57)), s68);
         dfa.addTransition(new Pair(s2, new Symbol((char)949)), s2);
         dfa.addTransition(new Pair(s2, new Symbol((char)65)), s49);
         dfa.addTransition(new Pair(s2, new Symbol((char)66)), s50);
         dfa.addTransition(new Pair(s2, new Symbol((char)67)), s51);
         dfa.addTransition(new Pair(s2, new Symbol((char)68)), s52);
         dfa.addTransition(new Pair(s2, new Symbol((char)69)), s53);
         dfa.addTransition(new Pair(s2, new Symbol((char)97)), s54);
         dfa.addTransition(new Pair(s2, new Symbol((char)98)), s55);
         dfa.addTransition(new Pair(s2, new Symbol((char)99)), s56);
         dfa.addTransition(new Pair(s2, new Symbol((char)100)), s57);
         dfa.addTransition(new Pair(s2, new Symbol((char)101)), s58);
         dfa.addTransition(new Pair(s2, new Symbol((char)48)), s59);
         dfa.addTransition(new Pair(s2, new Symbol((char)49)), s60);
         dfa.addTransition(new Pair(s2, new Symbol((char)50)), s61);
         dfa.addTransition(new Pair(s2, new Symbol((char)51)), s62);
         dfa.addTransition(new Pair(s2, new Symbol((char)52)), s63);
         dfa.addTransition(new Pair(s2, new Symbol((char)53)), s64);
         dfa.addTransition(new Pair(s2, new Symbol((char)54)), s65);
         dfa.addTransition(new Pair(s2, new Symbol((char)55)), s66);
         dfa.addTransition(new Pair(s2, new Symbol((char)56)), s67);
         dfa.addTransition(new Pair(s2, new Symbol((char)57)), s68);
     }

     @Override     public Token getToken() throws Exception {
         StringBuilder s = new StringBuilder();
         while((dfa.lastState() == null) || (!dfa.lastState().equals(DFA.deadState))) {
             consume();
             if (currentCharacter == -1) return Token.EOF_TOKEN;
             s.append((char)currentCharacter);
             dfa.simulate(s.toString()+((char)nextCharacter));
         }
         if (dfa.lastState().equals(DFA.deadState)) {
             if (dfa.simulate(s.toString())) {
                 return new Token(dfa.lastState().attached(), s.toString());
             }
         }
         throw new Exception("Invalid lexeme");
     }

     private void consume() throws Exception {
         currentCharacter = nextCharacter;
         nextCharacter = reader.read();
     }
}
