import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;
import src.Regexer;
import src.automatons.Automaton;
import src.automatons.DFA;
import src.automatons.NFA;
import src.automatons.NFABuilder;
import src.automatons.Pair;
import src.automatons.State;
import src.automatons.Symbol;

class ProyectoLexer {
private DFA dfa;

public ProyectoLexer() throws Exception {
     dfa = new DFA();
     State s1 = new State("1");
     dfa.addState(s1);
     dfa.changeInitialState(s1);
     State s2 = new State("2");
     dfa.addState(s2);
     s2.setAttached("id");
     dfa.addAcceptingState(s2);
     State s3 = new State("3");
     dfa.addState(s3);
     s3.setAttached("id");
     dfa.addAcceptingState(s3);
     State s4 = new State("4");
     dfa.addState(s4);
     s4.setAttached("IGNORE");
     dfa.addAcceptingState(s4);
     State s5 = new State("5");
     dfa.addState(s5);
     s5.setAttached("id");
     dfa.addAcceptingState(s5);
     State s6 = new State("6");
     dfa.addState(s6);
     s6.setAttached("id");
     dfa.addAcceptingState(s6);
     State s7 = new State("7");
     dfa.addState(s7);
     s7.setAttached("sum");
     dfa.addAcceptingState(s7);
     State s8 = new State("8");
     dfa.addState(s8);
     s8.setAttached("sum");
     dfa.addAcceptingState(s8);
     State s9 = new State("9");
     dfa.addState(s9);
     s9.setAttached("while");
     dfa.addAcceptingState(s9);
     State s10 = new State("10");
     dfa.addState(s10);
     s10.setAttached("if");
     dfa.addAcceptingState(s10);
     State s11 = new State("11");
     dfa.addState(s11);
     State s12 = new State("12");
     dfa.addState(s12);
     State s13 = new State("13");
     dfa.addState(s13);
     State s14 = new State("14");
     dfa.addState(s14);
     State s15 = new State("15");
     dfa.addState(s15);
     dfa.addTransition(new Pair(s1, new Symbol((char)105)), s11);
     dfa.addTransition(new Pair(s1, new Symbol((char)119)), s12);
     dfa.addTransition(new Pair(s1, new Symbol((char)97)), s2);
     dfa.addTransition(new Pair(s1, new Symbol((char)98)), s3);
     dfa.addTransition(new Pair(s1, new Symbol((char)32)), s4);
     dfa.addTransition(new Pair(s3, new Symbol((char)97)), s5);
     dfa.addTransition(new Pair(s3, new Symbol((char)98)), s6);
     dfa.addTransition(new Pair(s3, new Symbol((char)45)), s7);
     dfa.addTransition(new Pair(s3, new Symbol((char)43)), s8);
     dfa.addTransition(new Pair(s6, new Symbol((char)97)), s5);
     dfa.addTransition(new Pair(s6, new Symbol((char)98)), s6);
     dfa.addTransition(new Pair(s5, new Symbol((char)97)), s5);
     dfa.addTransition(new Pair(s5, new Symbol((char)98)), s6);
     dfa.addTransition(new Pair(s2, new Symbol((char)97)), s5);
     dfa.addTransition(new Pair(s2, new Symbol((char)98)), s6);
     dfa.addTransition(new Pair(s2, new Symbol((char)45)), s7);
     dfa.addTransition(new Pair(s2, new Symbol((char)43)), s8);
     dfa.addTransition(new Pair(s12, new Symbol((char)104)), s13);
     dfa.addTransition(new Pair(s13, new Symbol((char)105)), s14);
     dfa.addTransition(new Pair(s14, new Symbol((char)108)), s15);
     dfa.addTransition(new Pair(s15, new Symbol((char)101)), s9);
     dfa.addTransition(new Pair(s11, new Symbol((char)102)), s10);
}

}
